## Propriétés du serveur
server:
  port: 8280

# H2 Database
spring:
  datasource:
    url: jdbc:h2:mem:users
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

# Logging
logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR
    net:
      guides: DEBUG
